### ISSUE TITLE
Where can we find the files used by the generator?

### ISSUE THREAD

**Issue by Rezenders** [johaq/CommandGenerator#1]
Hi @johaq,

Where can we find the [files](https://github.com/johaq/CommandGenerator/blob/b8dfcc228053b6833c910ac7d375742167353385/generator.py#L77C27-L78C42) used by the generator? I.e., `names.md`, `location_names.md`, `room_names.md`, `test.md`. 

Thanks in advance,

Gustavo.

**Comment by johaq** [comment]
Here: https://github.com/johaq/CompetitionTemplate

**Comment by Rezenders** [comment]
Thanks
